---
interfaces:
  - name: Loopback0
    description: "Ansible:Loopback0"
    enabled: true
    ipv4:
      address: 10.10.10.1
      mask: 255.255.255.255
  - name: Ethernet0/1
    description: "Ansible:Connection to p_central_eth0/1"
    enabled: true
    ipv4:
      address: 10.1.0.0
      mask: 255.255.255.254
    ospf:
      network: "point-to-point"
      process:
        - id: 1
          area: 0
    mpls:
      ip:
        enabled: true

ospf:
  process:
    - id: 1
      router_id: "{{ (interfaces | selectattr('name', 'equalto', 'Loopback0') | first).ipv4.address }}"
      network:
        - prefix: "10.10.10.1"
          wildcard: "0.0.0.0"
          area: 0
        - prefix: "10.1.0.0"
          wildcard: "0.0.0.1"
          area: 0

mpls:
  enabled: true
  protocol: ldp

bgp:
  as_number: 65536
  router_id: "{{ (interfaces | selectattr('name', 'equalto', 'Loopback0') | first).ipv4.address }}"
  log_neighbor_changes: true
  neighbor:
    - address: "10.10.10.3"
      description: pe_east
      remote_as: 65536
      update_source: Loopback0
  address_family:
    - afi: vpnv4
      safi: unicast
      neighbor:
        - address: "10.10.10.3"
          activate: true
          send_community:
            extended: true
