---
interfaces:
  - name: Loopback0
    description: "Ansible:Loopback0"
    enabled: true
    ipv4:
      address: 10.10.10.2
      mask: 255.255.255.255
  - name: Ethernet0/1
    description: "Ansible:Connection to pe_west_eth0/1"
    enabled: true
    ipv4:
      address: 10.1.0.1
      mask: 255.255.255.254
    ospf:
      network: "point-to-point"
      process:
        - id: 1
          area: 0
    mpls:
      ip:
        enabled: true
  - name: Ethernet0/2
    description: "Ansible:Connection to pe_east_eth0/1"
    enabled: true
    ipv4:
      address: 10.1.0.3
      mask: 255.255.255.254
    ospf:
      network: "point-to-point"
      process:
        - id: 1
          area: 0
    mpls:
      ip:
        enabled: true

ospf:
  process:
    - id: 1
      router_id: "{{ (interfaces | selectattr('name', 'equalto', 'Loopback0') | first).ipv4.address }}"
      network:
        - prefix: "10.10.10.2"
          wildcard: "0.0.0.0"
          area: 0
        - prefix: "10.1.0.0"
          wildcard: "0.0.0.1"
          area: 0
        - prefix: "10.1.0.2"
          wildcard: "0.0.0.1"
          area: 0

mpls:
  enabled: true
  protocol: ldp
